# ubkg-front-end docker compose
services:
  ubkg-front-end:
    build:
      # Configure Compose for multi-architecture builds.
      # Prerequisites:
      # 1. Create an additional buildx builder by running
      #    docker buildx create --use
      # 2. Build tags for both the current version and "latest".
      tags:
        - docker.io/hubmap/ubkg-front-end:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    # Build the image with name and tag
    # Exit with an error message containing err if unset or empty in the environment
    image: hubmap/ubkg-front-end:latest