services:

  # The ubkg-front-end service contains the UI for UBKGBox.

  ubkg-front-end:
    hostname: ubkg-front-end
    container_name: ubkg-front-end
    # Map host machine port 7200 to container port 8080
    ports:
      - "7200:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
    restart: always